services:
  api:
    build:
      context: .
    command: ["./entrypoint.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - ENV=production
      - DATABASE_URL=postgresql://ai:ai@db:5432/ai
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app/backend
      - ./backend/migrations:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./entrypoint.sh:/app/entrypoint.sh

  redis:
    image: redis:7-alpine

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
