apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-orchestrator.fullname" . }}
  labels:
    app: {{ include "ai-orchestrator.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ai-orchestrator.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ai-orchestrator.name" . }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_URL
              value: redis://redis:6379/0
